### ISSUE TITLE
[WarpGUI] Player Heads Reset to Steve Heads on Server Restart

### ISSUE THREAD

**Issue by remiscarlet** [CodingAir/WarpSystem-IssueTracker#778]
**Describe the bug**
When setting a WarpGUI icon to a player head, the icon is reverted to a Steve head on server restart.

**To Reproduce**
1. Start fresh server with just WarpSystem
2. `/give @a player_head[profile={name:Remi_Scarlet}]` to get player head
3. Set warp icon to player head held in hand.
4. Confirm player head icon is as expected.
5. Restart server.
6. Player head icon is now a Steve head

**Expected behavior**
Player head metadata is preserved across server restarts

**Screenshots**
_Pre-Restart_
<img width="1728" alt="Screenshot 2024-09-21 at 8 32 15 PM" src="https://github.com/user-attachments/assets/007f45f2-8b22-45e7-858c-f8cb773c577c">

_Post-Restart_
<img width="1728" alt="Screenshot 2024-09-21 at 8 39 01 PM" src="https://github.com/user-attachments/assets/a96a2647-673e-42fa-91e0-cb34d3e84c50">

**Additional context**
`Memory/ActionIcons.yml` doesn't seem to store any metadata regarding the player head such as UUID/SkullOwner
```
- item:
    Type: PLAYER_HEAD
    Amount: 1
    HideStandardLore: true
    Name: Test Warp Icon
  name: Test Warp Icon
  slot: 9
  page: TestPage
  performed: 1
  actions:
  - value:
      destination:
        id: testwarp
        type: 1
```

Perhaps related to https://github.com/erikzimmermann/WarpSystem-IssueTracker/issues/563

**Server version**: `1.21.1` (WarpSystem `v5.1.14-free`)
**Discord contact**: `remiscarlet`
